version: '3.7'
services:
  mysql:
    image: mysql:8.0.21
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysqldb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  node-app:
    build: ..
    image: node-app:1.0
    ports:
      - '9999:9999'